:PROPERTIES:
:ID:       BB7E4400-1B8B-42D7-867E-D5C4639DD56F
:END:
#+title: ACT Therapy
* ACT Therapy
** Blog: How To Do Hard Things
https://every.to/no-small-plans/how-to-do-hard-things
*** Experiential Avoidance → Willingness
/Willingness/ is intentionally doing the things we don't want to do, but that we know will move us towards our goals.

What we fear can serve as a compass to what is important.

"What we want to learn to do is contact discomfort when it's in service of doing things that we care about."

"What are you unwilling to feel?" The answer becomes the focus of our work.
*** Fusion → Defusion
/Fusion/ is believing our thoughts are true, that our thoughts are reality.

/Defusion/ is recognizing that our thoughts are only mental constructs and are separate from reality.

Beware of:
- Reasons - "I can't do X because..."
- Judgments - "People always..."
- Rules - "I shouldn't feel Y" or "I have to work harder than others to be successful."

We should give weight to thoughts that move us towards our goals.
*** Past/Future → Present-Moment Awareness
/Past / future fusion/ is when we focus too much on thoughts about the past or the future.

Remember, thoughts about the past or future are mental constructs, just thoughts.

There is some value in considering the past and future, but at some point it takes away from the present.

"There comes a point where ruminating over the past or worrying about the future no longer pays dividends."

The present goal is to act well in the present.
*** Rigid Stories → Flexible Perspective-Taking
We tell ourselves /rigid stories/ about others, and also about ourselves.

This happens when we judge ourselves or others: "That person is dumb," but the truth is that person is complex with many different goals. "I am dumb," again, I am a complex person with strengths and weaknesses, but I am capable of many things.

Beware of flattening people into single word judgements. This is a sign of inaccurate thinking.

Remember Crucial Conversations, there are many possibilities when it comes to people, and with the correct approach we can probably find a way to get what we want.

In short, keep a flexible perspective about yourself and others.
*** Lack of Direction → Clear Values
"Moving toward values is about reconnecting our day-to-day activities to the things that matter most to us. It's about clarifying for ourselves what a life well-lived would look like, and then intentionally bringing those qualities into our life and work in the present."
**** Eulogy exercise
If you lived the life you wanted, what would your eulogy say?

If you died today, what would your eulogy say?

What can you do about the difference?
*** Inaction → Committed Action
"Committed action is about finding places in our lives where we might shift our behavior to be more aligned with our values. It's about using the skills above to work with whatever thoughts and feelings are sustaining unhelpful behaviors, and then taking small steps in new directions."

"Behavior change is often fragile toward the beginning, so the goal of the list above is to provide scaffolding for new behaviors until they start to become self-reinforcing. Ultimately, we want the new behavior to be intrinsically rewarding enough that it continues on its own."
**** Scaffolding
 - Reminders - using apps, timers, or other means to remind us of the new behavior
 - Records - keeping track of our behavior throughout the day
 - Rewards - giving ourselves positive reinforcement for engaging in a behavior
 - Routines - building the new behavior around an existing daily habit
 - Relationships - finding a friend to do the new behavior with, or who you can talk to about the progress you’re making
 - Reflecting - taking time to reflect on the progress you’re making through journaling, discussion with a friend, or in your mind
 - Restructuring - making changes to the environment to make it easier to do the new behavior – i.e., throwing out unhealthy food or preparing at night for a morning run

